language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  - cat /etc/issue
  - node -v
  - npm -v

install:
  - echo 'frank test'

script:
  - mvn clean package

after_script:
  - cat /home/travis/.npm/_logs/*.log

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - advenoh@gmail.com