language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
#cache:
#  directories:
#    - '$HOME/.m2/repository'

before_install:
  - cat /etc/issue
  - node -v
  - npm -v
  - sudo apt-get update
#  - sudo apt-get purge --auto-remove nodejs
#  - curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
#  - sudo apt-get -y install nodejs
#  - sudo apt-get -y install npm
  - sudo apt-get install build-essential libssl-dev
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - source ~/.bashrc
  - nvm --version
  - nvm install 10.15.1
  - node -v
  - npm -v
#  - cd frontend && npm install && cd ..
#  - npm install react-scripts

install:
  - echo 'frank test'

script:
  - mvn clean install

after_script:
  - cat /home/travis/.npm/_logs/*.log

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - advenoh@gmail.com