language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  - cat /etc/issue
  - node -v
  - npm -v
  - sudo apt-get update
  - apt-get purge --auto-remove nodejs
#  - sudo apt-get -y install build-essential libssl-dev
  - curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
  - sudo apt-get -y install nodejs
  - sudo apt-get -y install npm
  - node -v
  - npm -v

install:
  - echo 'frank test'

script:
  - mvn clean package

after_script:
  - cat /home/travis/.npm/_logs/*.log

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - advenoh@gmail.com