# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
#    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
#    - name: OS version
#      run : cat /etc/issue
    - name: node version
      run: |
        node -v
        npm -v
#    - name : cache clear
#      run: npm cache clean --force
#    - name: node install
#      run : npm install
#      working-directory: ./frontend
#    - name: npm run build
#      run: CI=false npm run build
#      working-directory: ./frontend
    - name: Generate the package
      run: CI=false mvn clean package --file pom.xml -Dmaven.test.skip=true
    - name: check the log file
      if: ${{ failure() }}
      run: cat /home/runner/.npm/_logs/*.log
#    - name : output
#      run: cat /home/runner/.npm/_logs/*.log
